### ISSUE TITLE
Workflow Example

### ISSUE THREAD

**Issue by andupotorac** [Extraltodeus/sigmas_tools_and_the_golden_scheduler#4]
Hey there. It would be great if you could share one of your workflows where you use this, so we can understand how it works. I was looking over Advanced PAG here where it mentioned your tool: https://github.com/pamparamm/sd-perturbed-attention/issues/13#issuecomment-2101672568.

But not sure how it would work.

**Comment by Extraltodeus** [comment]
Hello,

I'm not sure what you mean. They are all straight forward as schedulers that you can connect to an advanced sampler. What is it that you are looking for?

**Comment by andupotorac** [comment]
Maybe I need to look into it more, but I am not entirely sure where those values will come from and how they're to be applied. If you have any workflows that you already use this for, it would help!

**Comment by Extraltodeus** [comment]
> Maybe I need to look into it more, but I am not entirely sure where those values will come from and how they're to be applied. If you have any workflows that you already use this for, it would help!

The values are related to the sigma. Which is basically how much noise is removed at each step so to make the image. How much per step is defined by the scheduler.

I can't make a workflow rn but if you want to get a good idea then you can use the node from this repository which generates a graph from a schedule.

In general i just keep in mind that 14.61 is the max sigma for most models and then it decreases rapidly. ~7 for the second step.

Like really it should be more clear if you check a graph.

**Comment by andupotorac** [comment]
Thanks!
